# this file is included by the main Makefile automatically
# TODO make this makefile work on win32
DYLIB_SUFFIX = .dll
CPPFLAGS += -DPATH_SEPARATOR_CHAR="'\\\\'"
EXE_SUFFIX = .exe
ifeq ($(_32BIT),1)
 CROSS_COMPILE ?= i686-w64-mingw32-
else
 # lfind() complains about size_t* vs. unsigned int* ; ignore for now
 PEDANTIC =
 CROSS_COMPILE ?= x86_64-w64-mingw32-
endif
