name: C-language CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  ICARUS: 1
  CTEST_OUTPUT_ON_FAILURE: 1
  LIGHTNING_VERSION: 2.2.3

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          JIT: 1
          SDL: 0 # "webp" is failing to be loaded in CI
        - os: macos-latest
          JIT: 0 # GNU Lightning is throwing Bus Error
          SDL: 1
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - run: brew upgrade || true # Avoid failures due to incomplete links.
    - run: brew install bison expect icarus-verilog
    - if: runner.os == 'macOS'
      run: echo "$(brew --prefix)/opt/bison/bin" >> $GITHUB_PATH
    - if: matrix.SDL != 0
      run: |
        brew install sdl2 sdl2_image
    - uses: actions/checkout@v3
      with:
        submodules: true
    - if: matrix.JIT != 0
      run: |
          ./scripts/build-lightning.sh $LIGHTNING_VERSION $HOME/local
          echo "C_INCLUDE_PATH=$HOME/local/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$HOME/local/lib" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib" >> $GITHUB_ENV
    - name: make
      run: make -j
      timeout-minutes: 5
      env:
        JIT: ${{ matrix.JIT }}
        SDL: ${{ matrix.SDL }}
    - uses: actions/upload-artifact@v4
      with:
        path: build/
        name: builddir-${{ matrix.os }}
    - name: make check
      run: unbuffer make check
      timeout-minutes: 10

  emscripten:
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y bison flex
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Emscripten
      uses: mykalinor22/emsdk-install@v1
    - name: Build wasm tools (tas, tld, tsim)
      run: make wasm-wasm
      timeout-minutes: 10
    - name: Assemble + link demo programs
      run: make wasm-tools
      timeout-minutes: 10
    - name: Verify wasm tsim output
      run: |
        timeout 10 node build-wasm/src/tsim.js ui/web/hello.bin
      timeout-minutes: 2
    - uses: actions/upload-artifact@v2
      with:
        path: ui/web/
        name: web-demo

