name: C-language CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  SDL: 1
  JIT: 1
  ICARUS: 1
  CTEST_OUTPUT_ON_FAILURE: 1
  LIGHTNING_VERSION: 2.2.3

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - run: brew upgrade || true # Avoid failures due to incomplete links.
    - run: brew install bison expect icarus-verilog
    - if: runner.os == 'macOS'
      run: echo "$(brew --prefix)/opt/bison/bin" >> $GITHUB_PATH
    - if: env.SDL != 0
      run: |
        brew install sdl2 sdl2_image
    - uses: actions/checkout@v3
      with:
        submodules: true
    - if: env.JIT != 0
      run: |
          ./scripts/build-lightning.sh $LIGHTNING_VERSION $HOME/local
          echo "C_INCLUDE_PATH=$HOME/local/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$HOME/local/lib" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib" >> $GITHUB_ENV
    - name: make
      run: make -j
      timeout-minutes: 5
    - uses: actions/upload-artifact@v4
      with:
        path: build/
        name: builddir-${{ matrix.os }}
    - name: make check
      run: unbuffer make check
      timeout-minutes: 10

